language: node_js
node_js:
  - "10"

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn test
    - stage: deploy
      script:
        - yarn
        - yarn build
      deploy:
        - cd public
        - find . -wholename '*' -printf '%p\n' -type f -exec curl -sk sftp://${SFTP_HOST}:${SFTP_PORT}/~/html/{} -u ${SFTP_USER}:${SFTP_PASSWORD} -T {} --ftp-create-dirs\;

stages:
  - test
  - name: deploy
    if: tag IS present