language: node_js
node_js:
  - "17"

sudo: required

cache: yarn

jobs:
  include:
    - stage: build
      script:
        - yarn
      deploy:
        provider: script
        skip_cleanup: true
        script: make frontend &&
          docker build --no-cache=true -t gradinware-server . &&
          docker login www.gradinware.com --username '${REGISTRY_USERNAME}' --password '${REGISTRY_PASSWORD}' &&
          docker tag gradinware-server www.gradinware.com/gradinware/server:${TRAVIS_TAG} &&
          docker tag gradinware-server www.gradinware.com/gradinware/server:latest &&
          docker push www.gradinware.com/gradinware/server:${TRAVIS_TAG} &&
          docker push www.gradinware.com/gradinware/server
        on:
          tags: true

stages:
  - build
