language: node_js
node_js:
  - "10"

sudo: required

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn test
    - stage: build
      script:
        - yarn
        - yarn build
      before_deploy: sudo apt-get update && sudo apt-get install -y sshpass
      deploy:
        provider: script
        skip_cleanup: true
        script: make create &&
          docker login www.gradinware.com --username '${REGISTRY_USERNAME}' --password '${REGISTRY_PASSWORD}' &&
          docker tag gradinware-server www.gradinware.com/gradinware/server:latest &&
          docker push www.gradinware.com/gradinware/server:latest &&
          sshpass -p ${SFTP_PASSWORD} ssh -p 2345 -oStrictHostKeyChecking=no ${SFTP_USER}@${SFTP_HOST} "mkdir -p src/ui/public" &&
          sshpass -p ${SFTP_PASSWORD} scp -P 2345 -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null data/* ${SFTP_USER}@${SFTP_HOST}:data
          sshpass -p ${SFTP_PASSWORD} scp -P 2345 -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null src/ui/public/* ${SFTP_USER}@${SFTP_HOST}:src/ui/public
        on:
          tags: true

stages:
  - test
  - build