language: node_js
node_js:
  - "10"

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn test
    - stage: build
      script:
        - yarn
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: /bin/bash ./scripts/deploy.sh
        on:
          tags: true

stages:
  - test
  - build