version: '3'

services:
  server:
    image: localhost:5000/gradinware/server:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
    - "3000:5000"
     volumes:
    - ../src/ui/public:/public:ro